version: 0.2

run-as: root

phases:
  install:
    run-as: root
    on-failure: ABORT
    runtime-versions:
      python: 3.8
    commands:
      - pip -U install pytest
  pre_build:
    run-as: root
    on-failure: ABORT
    commands:
      - pytest -q ./lambda/test_app.py

  build:
    run-as: root
    on-failure: ABORT
    commands:
      - aws cloudformation package --template-file template.yaml --output-template-file outputTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml
